# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='referencing_messages', to='chats.Topic'),
        ),
    ]
