# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_profile_online'),
        ('interactive', '0003_message_seen_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user2',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='chats.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='chats.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(choices=[('FOL', 'follow'), ('LIK', 'like')], max_length=3),
        ),
    ]
