# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_profile_online'),
        ('interactive', '0004_auto_20180919_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chatgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup'),
        ),
    ]
