# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_notification_chatgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(choices=[('FOL', 'follow'), ('LIK', 'like'), ('FOLCG', 'follow chatgroup')], max_length=5),
        ),
    ]
