# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
